version: '3'

services:
  openvpn-as:
    image: openvpn/openvpn-as
    container_name: openvpn-as
    devices:
      - /dev/net/tun
    cap_add:
      - MKNOD
      - NET_ADMIN
    volumes:
      - openvpn-as-data:/openvpn
    restart: unless-stopped

volumes:
  openvpn-as-data:
