version: '3'

services:
  openvpn-as:
    image: openvpn/openvpn-as
    container_name: openvpn-as
    devices:
      - /dev/net/tun
    cap_add:
      - MKNOD
      - NET_ADMIN
    ports:
      - 943:943
      - 443:443
      - 1194:1194/udp
    volumes:
      - openvpn-as-data:/openvpn
    restart: unless-stopped
